#!/bin/sh

###########################
## ENVIRONMENT

export SHELL_NAME="$( echo "$SHELL" | grep -o '[^/]*$' )"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

if [ ! -z "$(which nvim)" ]; then
	export EDITOR="nvim"
elif [ ! -z "$(which vim)" ]; then
	export EDITOR="vim"
else
	export EDITOR="nano"
fi

[ ! -z "$(which ssh-agent)" ] && eval "$(ssh-agent -s)" 1>/dev/null


###########################
## PATHS

shift $#
set -- /usr/local/go/bin ~/go/bin ~/.cargo/bin ~/.local/bin ~/.local/scripts ~/bin ~/.bin ~/.dotfiles/scripts
for p in "$@"; do
	if [ -d "$p" ]; then
		export PATH=$p:$PATH
	fi
done
shift $#


###########################
## FUNCTIONS

f() {
	find . -iname "*$1*"
}

fe() {
	find . -iname "*$1*" | fzf -i | xargs -o $EDITOR
}

fea() {
	find . -iname "*$1*" | xargs -o $EDITOR
}


###########################
## ALIASES

alias e="$EDITOR"
alias o="open"

alias ls="ls --color=auto"
alias lst="ls -1t"
alias l="ls -lah"
alias lt="ls -laht"

if [ "$(uname)" = "Linux" ]; then
	alias ls="ls --color=auto --group-directories-first"
fi

alias grep="grep --color=auto"
alias egrep="grep -E"
alias fgrep="grep -F"

alias cd..="cd .."
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias g="git"
alias gs="git status"
alias ga="git add"
alias ga.="git add ."
alias gaa="git add ."
alias gap="git add -p"
alias gap.="git add -p ."
alias gd="git diff"
alias gds="git diff --staged"
alias grs="git restore --staged"
alias grs.="git restore --staged ."
alias gc="git commit"
alias gcm="git commit --message"
alias gl="git log"
alias gls="git log --stat"
alias gll="git log --graph --abbrev-commit --pretty=format:'%Cred%h%Creset - %s %Cgreen(%cr) %C(bold blue)<%an>%Creset %C(yellow)%d%Creset'"
alias glp="git log --patch"
alias gla="git log --stat --patch"
alias glom="git log origin/master.."
alias gfa="git fetch --all --prune"
alias gp="git push"
alias gpom="git push -u origin/master"
alias grom="git rebase origin/master --autostash"
alias gromi="git rebase origin/master -i --autostash"
alias gbpurge='git branch --merged | grep -Ev "(\*|master|develop|staging)" | xargs -n 1 git branch -d'

# alias ssh-cache="ssh-add ~/.ssh/id_rsa"


###########################
## SHORTCUTS

case "$SHELL_NAME" in
	bash )
		bind -x '"\C-t":"tmux-select"'
		bind -x '"\C-e":"fzf --print0 | xargs -0 -o vim"'
		;;

	zsh )
		# basic key bindings
		bindkey "^[[H" beginning-of-line
		bindkey "^[[F" end-of-line
		bindkey "^P" history-search-backward
		bindkey "^N" history-search-forward

		# tmux-select
		function _tmux-select {
			zle push-input
			BUFFER="tmux-select"
			zle accept-line
		}
		zle -N _tmux-select
		bindkey "^t" _tmux-select

		# fzf edit
		function _fzf-edit {
			zle push-input
			BUFFER="fzf --print0 | xargs -0 -o vim"
			zle accept-line
		}
		zle -N _fzf-edit
		bindkey "^e" _fzf-edit
		;;
esac


###########################
## SHELL OPTIONS


case "$SHELL_NAME" in
	bash )
		;;

	zsh )
		autoload -U colors && colors
		autoload -Uz compinit && compinit

		setopt AUTO_CD
		setopt NO_CASE_GLOB
		setopt EXTENDED_HISTORY

		export SAVEHIST=100000
		export HISTFILE=~/.zsh_history
		;;
esac
