#!/usr/bin/env bash

UNIX_TIMESTAMP=
VERBOSE=
FNAMES=()
CP=cp

usage() {
	echo "Usage: bak [-u | --unix | -v | --verbose] [<filenames>]"
}

while [ "$1" != "" ]
do
	case $1 in
		-u | --unix )
			UNIX_TIMESTAMP=1
			;;
		-v | --verbose )
			VERBOSE=1
			;;
		-h | --help )
			usage
			exit 0
			;;
		* )
			FNAMES+=("$1")
			;;
	esac
	shift
done

if [ $VERBOSE ]; then
	CP="cp -v"
fi

for fn in "${FNAMES[@]}"
do
	if [ ! -f $fn ]
	then
		>&2 echo "ERROR: File not found: \"$fn\""
		exit 1
	else
		if [ $UNIX_TIMESTAMP ]
		then
			$CP "$fn" "$fn.bak_$(date +"%s")"
		else
			if [ ! -f "$fn.bak" ]
			then
				$CP "$fn" "$fn.bak"
			else
				CNTR=1
				while [ -f "$fn.bak$CNTR" ]
				do
					((CNTR++))
				done
				$CP "$fn" "$fn.bak$CNTR"
			fi
		fi
	fi
done
