#!/usr/bin/env bash

UNIX_TIMESTAMP=
FNAMES=()

usage() {
	echo "Usage: bak [-u | --unix] [<filenames>]"
}

while [ "$1" != "" ]
do
	case $1 in
		-u | --unix )
			UNIX_TIMESTAMP=1
			;;
		-h | --help )
			usage
			exit 0
			;;
		* )
			FNAMES+=("$1")
			;;
	esac
	shift
done

for fn in "${FNAMES[@]}"
do
	if [ ! -f $fn ]
	then
		>&2 echo "ERROR: File not found: \"$fn\""
		exit 1
	else
		if [ $UNIX_TIMESTAMP ]
		then
			cp "$fn" "$fn.bak_$(date +"%s")"
		else
			if [ ! -f "$fn.bak" ]
			then
				cp "$fn" "$fn.bak"
			else
				CNTR=1
				while [ -f "$fn.bak$CNTR" ]
				do
					((CNTR++))
				done
				cp "$fn" "$fn.bak$CNTR"
			fi
		fi
	fi
done
