#!/bin/sh

(
	cd "$HOME/notes"

	case "$1" in
		grep | g )
			shift
			if [ -x "$(which rg)" ]; then
				rg "$1"
			else
				grep -nir --color=always -e "$1" .
			fi
			;;
		* )
			fname="$(fzf --print-query | tail -1)"
			if [ ! -z "$fname" ]; then
				vim "$fname"
			fi
			;;
	esac
)
