#!/bin/sh

if [ -x "$(which apt)" ]; then
    echo "[*] Updating APT"
    sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y
fi

if [ -x "$(which brew)" ]; then
    echo "[*] Updating homebrew"
    brew update && brew upgrade
fi
